services:
  dagster:
    build: .
    container_name: dagster_data_provenance_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DAGSTER_HOME: /app
    depends_on:
      - postgres
    restart: on-failure

  daemon:
    build: .
    container_name: dagster_data_provenance_daemon
    command: dagster-daemon run
    volumes:
      - .:/app
    environment:
      DAGSTER_HOME: /app
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:13
    container_name: dagster_data_provenance_postgres
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      POSTGRES_DB: dagster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pipelines/weather_daily/init_db:/docker-entrypoint-initdb.d

  streamlit:
    build: .
    container_name: dagster_data_provenance_streamlit
    command: streamlit run visualization/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    depends_on:
      - postgres
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: dagster_data_provenance_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
