services:
  dagster:
    build: .
    container_name: dagster_data_provenance_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - postgres

  daemon:
    build: .
    container_name: dagster_data_provenance_daemon
    command: dagster-daemon run
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: dagster_data_provenance_postgres
    env_file: .env
    ports:
      - "5432:5432"
